#!/bin/bash
# build-project --- Build the project from sources.
set -e

cd $PROJ_DIR

rm -rf lib

echo -e "\nCompiling TypeScript files ..."
tsc

browserify lib/checkin.js -o app/scripts/checkin.js

echo -e "\nPacking files for browser tests ..."
for file in lib/test/*-test.js; do
  base="$(basename "$file")"
  echo -e "\nBrowserify $file ..."
  browserify "$file" -o "app/scripts/$base"
done
