#!/bin/bash
# build-project --- Build the project from sources.
set -e
export TOOLS_DIR="$(unset CDPATH; cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
source $TOOLS_DIR/use

cd $PROJ_DIR

rm -rf lib

echo -e "\nCompiling TypeScript files ..."
tsc

echo -e "\nBrowserify packaging ..."

TARGET="app/scripts/index.js"
browserify lib/checkin.js -o "$TARGET"
ls -l $TARGET

for file in lib/test/*-test.js; do
  base="$(basename "$file")"
  TARGET="app/scripts/$base"
  browserify "$file" -o "$TARGET"
  ls -l $TARGET
done
