#!/bin/bash
# configure-project --- Configure repository dependencies for building and tests.
set -e

cd $PROJ_DIR

CONFIG_FILE="$PROJ_DIR/.firebaserc"

echo "Updating (installing) dependencies via npm ..."
npm update

# Display package version state
npm outdated

if [[ "$1" == "--force" ]]; then
  shift
  echo "Forcing re-configuration..."
  rm "$CONFIG_FILE"
fi

if [ ! -f "$CONFIG_FILE" ]; then
  echo "Project configuration missing ... add a 'testing' firebase configuration."
  firebase use --add
  cat "$CONFIG_FILE"
  exit 0
fi

set-config
