#!/bin/bash
# deploy-project --- Build and deploy project to hosting.
set -e

cd $PROJ_DIR

ENVIRONMENT="$(cat configs/current)"

if ! yes-or-no "Deploy to the $ENVIRONMENT environment"; then
  echo "Aborting deployment..."
  echo "Run set-config to change deployment environment."
  exit 1
fi

build-project
firebase deploy -P "$ENVIRONMENT"
