#!/bin/bash
# set-config --- Set configuration of site (testing, staging, or production).
set -e

cd $PROJ_DIR

if [[ "$1" != "" ]]; then
  ENVIRONMENT="$1"
  shift
else
  if [[ -f configs/current ]]; then
    ENVIRONMENT="$(cat configs/current)"
  else
    ENVIRONMENT="testing"
  fi

  read -p "Environment (testing|staging|production - default $ENVIRONMENT): " NEW_ENV
  if [[ "$NEW_ENV" != "" ]]; then
    ENVIRONMENT="$NEW_ENV"
  fi
fi

mkdir -p "$PROJ_DIR/configs"
CONFIG_FILE="$PROJ_DIR/configs/${ENVIRONMENT}.ts"

if [[ ! -f "$CONFIG_FILE" ]]; then
 echo "Missing configuration file $CONFIG_FILE"
 extract-config "$CONFIG_FILE"
fi

echo "$ENVIRONMENT" > configs/current
ln -sf "$CONFIG_FILE" src/config.ts

echo "Current configuration: $ENVIRONMENT"
cat src/config.ts
